FROM python:3.11

ARG ID=0
ARG PORT=5119
ARG IP=0.0.0.0

ENV ID=$ID
ENV PORT=$PORT
ENV IP=$IP
ENV PYTHONUNBUFFERED=1

WORKDIR /reverse_proxy

COPY reverse_proxy ./

RUN pip install --no-cache-dir -r requirements.txt

CMD python3 main.py --id $ID --port $PORT --ip $IP
